// US Cities with population 50,000+ by State
// This file contains major US cities for autocomplete functionality
// Can be expanded or replaced with API calls for complete data

export interface USCity {
  name: string
  state: string
  stateAbbr: string
  population: number
}

// Major US cities with population 50,000+ organized by state
// This is a comprehensive but not exhaustive list - can be expanded or replaced with API
export const usCitiesByState: Record<string, USCity[]> = {
  'AL': [
    { name: 'Birmingham', state: 'Alabama', stateAbbr: 'AL', population: 200733 },
    { name: 'Montgomery', state: 'Alabama', stateAbbr: 'AL', population: 200603 },
    { name: 'Mobile', state: 'Alabama', stateAbbr: 'AL', population: 187041 },
    { name: 'Huntsville', state: 'Alabama', stateAbbr: 'AL', population: 215006 },
    { name: 'Tuscaloosa', state: 'Alabama', stateAbbr: 'AL', population: 101129 },
    { name: 'Hoover', state: 'Alabama', stateAbbr: 'AL', population: 92419 },
    { name: 'Auburn', state: 'Alabama', stateAbbr: 'AL', population: 76840 },
    { name: 'Dothan', state: 'Alabama', stateAbbr: 'AL', population: 71402 },
  ],
  'AZ': [
    { name: 'Phoenix', state: 'Arizona', stateAbbr: 'AZ', population: 1608139 },
    { name: 'Tucson', state: 'Arizona', stateAbbr: 'AZ', population: 548073 },
    { name: 'Mesa', state: 'Arizona', stateAbbr: 'AZ', population: 504258 },
    { name: 'Chandler', state: 'Arizona', stateAbbr: 'AZ', population: 275987 },
    { name: 'Scottsdale', state: 'Arizona', stateAbbr: 'AZ', population: 241361 },
    { name: 'Glendale', state: 'Arizona', stateAbbr: 'AZ', population: 248325 },
    { name: 'Gilbert', state: 'Arizona', stateAbbr: 'AZ', population: 267918 },
    { name: 'Tempe', state: 'Arizona', stateAbbr: 'AZ', population: 195805 },
    { name: 'Peoria', state: 'Arizona', stateAbbr: 'AZ', population: 190985 },
    { name: 'Surprise', state: 'Arizona', stateAbbr: 'AZ', population: 147965 },
    { name: 'Yuma', state: 'Arizona', stateAbbr: 'AZ', population: 100064 },
    { name: 'Avondale', state: 'Arizona', stateAbbr: 'AZ', population: 87931 },
    { name: 'Goodyear', state: 'Arizona', stateAbbr: 'AZ', population: 95294 },
    { name: 'Buckeye', state: 'Arizona', stateAbbr: 'AZ', population: 91502 },
    { name: 'Flagstaff', state: 'Arizona', stateAbbr: 'AZ', population: 76831 },
    { name: 'Lake Havasu City', state: 'Arizona', stateAbbr: 'AZ', population: 57144 },
    { name: 'Casa Grande', state: 'Arizona', stateAbbr: 'AZ', population: 57536 },
    { name: 'Maricopa', state: 'Arizona', stateAbbr: 'AZ', population: 62720 },
    { name: 'Sierra Vista', state: 'Arizona', stateAbbr: 'AZ', population: 44820 },
    { name: 'Queen Creek', state: 'Arizona', stateAbbr: 'AZ', population: 66282 },
    { name: 'Prescott', state: 'Arizona', stateAbbr: 'AZ', population: 45331 },
    { name: 'Prescott Valley', state: 'Arizona', stateAbbr: 'AZ', population: 48126 },
    { name: 'Bullhead City', state: 'Arizona', stateAbbr: 'AZ', population: 44530 },
  ],
  'CA': [
    { name: 'Los Angeles', state: 'California', stateAbbr: 'CA', population: 3898747 },
    { name: 'San Diego', state: 'California', stateAbbr: 'CA', population: 1423851 },
    { name: 'San Jose', state: 'California', stateAbbr: 'CA', population: 1021795 },
    { name: 'San Francisco', state: 'California', stateAbbr: 'CA', population: 873965 },
    { name: 'Fresno', state: 'California', stateAbbr: 'CA', population: 542107 },
    { name: 'Sacramento', state: 'California', stateAbbr: 'CA', population: 524943 },
    { name: 'Long Beach', state: 'California', stateAbbr: 'CA', population: 456062 },
    { name: 'Oakland', state: 'California', stateAbbr: 'CA', population: 433031 },
    { name: 'Bakersfield', state: 'California', stateAbbr: 'CA', population: 384145 },
    { name: 'Anaheim', state: 'California', stateAbbr: 'CA', population: 346824 },
    { name: 'Santa Ana', state: 'California', stateAbbr: 'CA', population: 332318 },
    { name: 'Riverside', state: 'California', stateAbbr: 'CA', population: 314998 },
    { name: 'Stockton', state: 'California', stateAbbr: 'CA', population: 310496 },
    { name: 'Irvine', state: 'California', stateAbbr: 'CA', population: 307670 },
    { name: 'Chula Vista', state: 'California', stateAbbr: 'CA', population: 275487 },
    { name: 'Fremont', state: 'California', stateAbbr: 'CA', population: 230504 },
    { name: 'San Bernardino', state: 'California', stateAbbr: 'CA', population: 222101 },
    { name: 'Modesto', state: 'California', stateAbbr: 'CA', population: 218464 },
    { name: 'Fontana', state: 'California', stateAbbr: 'CA', population: 208393 },
    { name: 'Oxnard', state: 'California', stateAbbr: 'CA', population: 202063 },
    { name: 'Moreno Valley', state: 'California', stateAbbr: 'CA', population: 208634 },
    { name: 'Huntington Beach', state: 'California', stateAbbr: 'CA', population: 198711 },
    { name: 'Glendale', state: 'California', stateAbbr: 'CA', population: 196543 },
    { name: 'Santa Clarita', state: 'California', stateAbbr: 'CA', population: 228673 },
    { name: 'Garden Grove', state: 'California', stateAbbr: 'CA', population: 172646 },
    { name: 'Oceanside', state: 'California', stateAbbr: 'CA', population: 174068 },
    { name: 'Rancho Cucamonga', state: 'California', stateAbbr: 'CA', population: 174453 },
    { name: 'Santa Rosa', state: 'California', stateAbbr: 'CA', population: 178127 },
    { name: 'Ontario', state: 'California', stateAbbr: 'CA', population: 175265 },
    { name: 'Lancaster', state: 'California', stateAbbr: 'CA', population: 157601 },
    { name: 'Elk Grove', state: 'California', stateAbbr: 'CA', population: 176124 },
    { name: 'Palmdale', state: 'California', stateAbbr: 'CA', population: 169450 },
    { name: 'Corona', state: 'California', stateAbbr: 'CA', population: 157136 },
    { name: 'Salinas', state: 'California', stateAbbr: 'CA', population: 163542 },
    { name: 'Pomona', state: 'California', stateAbbr: 'CA', population: 151713 },
    { name: 'Hayward', state: 'California', stateAbbr: 'CA', population: 162954 },
    { name: 'Escondido', state: 'California', stateAbbr: 'CA', population: 151038 },
    { name: 'Torrance', state: 'California', stateAbbr: 'CA', population: 141126 },
    { name: 'Sunnyvale', state: 'California', stateAbbr: 'CA', population: 155805 },
    { name: 'Orange', state: 'California', stateAbbr: 'CA', population: 139911 },
    { name: 'Fullerton', state: 'California', stateAbbr: 'CA', population: 135161 },
    { name: 'Pasadena', state: 'California', stateAbbr: 'CA', population: 138699 },
    { name: 'Thousand Oaks', state: 'California', stateAbbr: 'CA', population: 126966 },
    { name: 'Visalia', state: 'California', stateAbbr: 'CA', population: 141384 },
    { name: 'Simi Valley', state: 'California', stateAbbr: 'CA', population: 125613 },
    { name: 'Concord', state: 'California', stateAbbr: 'CA', population: 129295 },
    { name: 'Roseville', state: 'California', stateAbbr: 'CA', population: 147773 },
    { name: 'Vallejo', state: 'California', stateAbbr: 'CA', population: 126090 },
    { name: 'Victorville', state: 'California', stateAbbr: 'CA', population: 134810 },
    { name: 'Santa Clara', state: 'California', stateAbbr: 'CA', population: 127647 },
    { name: 'Fairfield', state: 'California', stateAbbr: 'CA', population: 119881 },
    { name: 'Inglewood', state: 'California', stateAbbr: 'CA', population: 107762 },
    { name: 'El Monte', state: 'California', stateAbbr: 'CA', population: 109450 },
    { name: 'Ventura', state: 'California', stateAbbr: 'CA', population: 110763 },
    { name: 'Santa Monica', state: 'California', stateAbbr: 'CA', population: 93076 },
    { name: 'West Covina', state: 'California', stateAbbr: 'CA', population: 109501 },
    { name: 'Richmond', state: 'California', stateAbbr: 'CA', population: 114783 },
    { name: 'Antioch', state: 'California', stateAbbr: 'CA', population: 115291 },
    { name: 'Daly City', state: 'California', stateAbbr: 'CA', population: 104901 },
    { name: 'Berkeley', state: 'California', stateAbbr: 'CA', population: 124321 },
    { name: 'San Mateo', state: 'California', stateAbbr: 'CA', population: 105661 },
    { name: 'Rialto', state: 'California', stateAbbr: 'CA', population: 104026 },
    { name: 'Riverside', state: 'California', stateAbbr: 'CA', population: 314998 },
    { name: 'Carlsbad', state: 'California', stateAbbr: 'CA', population: 114746 },
    { name: 'Chico', state: 'California', stateAbbr: 'CA', population: 101475 },
    { name: 'Livermore', state: 'California', stateAbbr: 'CA', population: 87386 },
    { name: 'Compton', state: 'California', stateAbbr: 'CA', population: 95840 },
    { name: 'Temecula', state: 'California', stateAbbr: 'CA', population: 110003 },
    { name: 'Murrieta', state: 'California', stateAbbr: 'CA', population: 114706 },
    { name: 'Jurupa Valley', state: 'California', stateAbbr: 'CA', population: 105053 },
    { name: 'Napa', state: 'California', stateAbbr: 'CA', population: 79582 },
    { name: 'Redding', state: 'California', stateAbbr: 'CA', population: 93311 },
    { name: 'Clovis', state: 'California', stateAbbr: 'CA', population: 120124 },
    { name: 'Burbank', state: 'California', stateAbbr: 'CA', population: 107337 },
    { name: 'Downey', state: 'California', stateAbbr: 'CA', population: 114355 },
    { name: 'El Cajon', state: 'California', stateAbbr: 'CA', population: 106215 },
    { name: 'San Leandro', state: 'California', stateAbbr: 'CA', population: 91008 },
    { name: 'Whittier', state: 'California', stateAbbr: 'CA', population: 87281 },
    { name: 'Citrus Heights', state: 'California', stateAbbr: 'CA', population: 87856 },
    { name: 'Hawthorne', state: 'California', stateAbbr: 'CA', population: 85053 },
    { name: 'Lakewood', state: 'California', stateAbbr: 'CA', population: 81603 },
    { name: 'Alhambra', state: 'California', stateAbbr: 'CA', population: 82869 },
    { name: 'Redwood City', state: 'California', stateAbbr: 'CA', population: 84815 },
    { name: 'Buena Park', state: 'California', stateAbbr: 'CA', population: 82782 },
    { name: 'Menifee', state: 'California', stateAbbr: 'CA', population: 102527 },
    { name: 'Hemet', state: 'California', stateAbbr: 'CA', population: 89833 },
    { name: 'Lakewood', state: 'California', stateAbbr: 'CA', population: 81603 },
    { name: 'Merced', state: 'California', stateAbbr: 'CA', population: 87275 },
    { name: 'Chino', state: 'California', stateAbbr: 'CA', population: 91721 },
    { name: 'Tracy', state: 'California', stateAbbr: 'CA', population: 93782 },
    { name: 'Indio', state: 'California', stateAbbr: 'CA', population: 89932 },
    { name: 'Baldwin Park', state: 'California', stateAbbr: 'CA', population: 72394 },
    { name: 'Chino Hills', state: 'California', stateAbbr: 'CA', population: 78351 },
    { name: 'Upland', state: 'California', stateAbbr: 'CA', population: 79404 },
    { name: 'Norwalk', state: 'California', stateAbbr: 'CA', population: 102773 },
    { name: 'Folsom', state: 'California', stateAbbr: 'CA', population: 80872 },
    { name: 'Milpitas', state: 'California', stateAbbr: 'CA', population: 80183 },
    { name: 'San Marcos', state: 'California', stateAbbr: 'CA', population: 94833 },
    { name: 'Watsonville', state: 'California', stateAbbr: 'CA', population: 53000 },
    { name: 'Redondo Beach', state: 'California', stateAbbr: 'CA', population: 71683 },
    { name: 'Tulare', state: 'California', stateAbbr: 'CA', population: 70933 },
  ],
  'CO': [
    { name: 'Denver', state: 'Colorado', stateAbbr: 'CO', population: 715522 },
    { name: 'Colorado Springs', state: 'Colorado', stateAbbr: 'CO', population: 478961 },
    { name: 'Aurora', state: 'Colorado', stateAbbr: 'CO', population: 386261 },
    { name: 'Fort Collins', state: 'Colorado', stateAbbr: 'CO', population: 169810 },
    { name: 'Lakewood', state: 'Colorado', stateAbbr: 'CO', population: 155984 },
    { name: 'Thornton', state: 'Colorado', stateAbbr: 'CO', population: 141867 },
    { name: 'Arvada', state: 'Colorado', stateAbbr: 'CO', population: 124402 },
    { name: 'Westminster', state: 'Colorado', stateAbbr: 'CO', population: 116317 },
    { name: 'Pueblo', state: 'Colorado', stateAbbr: 'CO', population: 111876 },
    { name: 'Greeley', state: 'Colorado', stateAbbr: 'CO', population: 108795 },
    { name: 'Boulder', state: 'Colorado', stateAbbr: 'CO', population: 108250 },
    { name: 'Longmont', state: 'Colorado', stateAbbr: 'CO', population: 98885 },
    { name: 'Loveland', state: 'Colorado', stateAbbr: 'CO', population: 76005 },
    { name: 'Grand Junction', state: 'Colorado', stateAbbr: 'CO', population: 65158 },
    { name: 'Broomfield', state: 'Colorado', stateAbbr: 'CO', population: 74112 },
    { name: 'Commerce City', state: 'Colorado', stateAbbr: 'CO', population: 62250 },
  ],
  'FL': [
    { name: 'Jacksonville', state: 'Florida', stateAbbr: 'FL', population: 949611 },
    { name: 'Miami', state: 'Florida', stateAbbr: 'FL', population: 442241 },
    { name: 'Tampa', state: 'Florida', stateAbbr: 'FL', population: 384959 },
    { name: 'Orlando', state: 'Florida', stateAbbr: 'FL', population: 307573 },
    { name: 'St. Petersburg', state: 'Florida', stateAbbr: 'FL', population: 258308 },
    { name: 'Hialeah', state: 'Florida', stateAbbr: 'FL', population: 223109 },
    { name: 'Tallahassee', state: 'Florida', stateAbbr: 'FL', population: 196169 },
    { name: 'Fort Lauderdale', state: 'Florida', stateAbbr: 'FL', population: 182760 },
    { name: 'Port St. Lucie', state: 'Florida', stateAbbr: 'FL', population: 204851 },
    { name: 'Cape Coral', state: 'Florida', stateAbbr: 'FL', population: 194016 },
    { name: 'Pembroke Pines', state: 'Florida', stateAbbr: 'FL', population: 171178 },
    { name: 'Hollywood', state: 'Florida', stateAbbr: 'FL', population: 153067 },
    { name: 'Miramar', state: 'Florida', stateAbbr: 'FL', population: 134721 },
    { name: 'Gainesville', state: 'Florida', stateAbbr: 'FL', population: 141085 },
    { name: 'Coral Springs', state: 'Florida', stateAbbr: 'FL', population: 134394 },
    { name: 'Miami Gardens', state: 'Florida', stateAbbr: 'FL', population: 111640 },
    { name: 'Clearwater', state: 'Florida', stateAbbr: 'FL', population: 117292 },
    { name: 'Palm Bay', state: 'Florida', stateAbbr: 'FL', population: 119760 },
    { name: 'West Palm Beach', state: 'Florida', stateAbbr: 'FL', population: 117415 },
    { name: 'Pompano Beach', state: 'Florida', stateAbbr: 'FL', population: 112046 },
    { name: 'Lakeland', state: 'Florida', stateAbbr: 'FL', population: 112641 },
    { name: 'Davie', state: 'Florida', stateAbbr: 'FL', population: 105691 },
    { name: 'Miami Beach', state: 'Florida', stateAbbr: 'FL', population: 82221 },
    { name: 'Sunrise', state: 'Florida', stateAbbr: 'FL', population: 97171 },
    { name: 'Plantation', state: 'Florida', stateAbbr: 'FL', population: 95473 },
    { name: 'Boca Raton', state: 'Florida', stateAbbr: 'FL', population: 97576 },
    { name: 'Deltona', state: 'Florida', stateAbbr: 'FL', population: 93440 },
    { name: 'Largo', state: 'Florida', stateAbbr: 'FL', population: 82975 },
    { name: 'Deerfield Beach', state: 'Florida', stateAbbr: 'FL', population: 80018 },
    { name: 'Boynton Beach', state: 'Florida', stateAbbr: 'FL', population: 80680 },
    { name: 'Fort Myers', state: 'Florida', stateAbbr: 'FL', population: 86395 },
    { name: 'Kissimmee', state: 'Florida', stateAbbr: 'FL', population: 72178 },
    { name: 'Homestead', state: 'Florida', stateAbbr: 'FL', population: 80531 },
    { name: 'Tamarac', state: 'Florida', stateAbbr: 'FL', population: 71341 },
    { name: 'Delray Beach', state: 'Florida', stateAbbr: 'FL', population: 66320 },
    { name: 'Daytona Beach', state: 'Florida', stateAbbr: 'FL', population: 72393 },
    { name: 'North Miami', state: 'Florida', stateAbbr: 'FL', population: 60239 },
    { name: 'Wellington', state: 'Florida', stateAbbr: 'FL', population: 61098 },
    { name: 'Jupiter', state: 'Florida', stateAbbr: 'FL', population: 61347 },
    { name: 'Ocala', state: 'Florida', stateAbbr: 'FL', population: 63891 },
    { name: 'Port Orange', state: 'Florida', stateAbbr: 'FL', population: 62415 },
    { name: 'Sanford', state: 'Florida', stateAbbr: 'FL', population: 61000 },
  ],
  'GA': [
    { name: 'Atlanta', state: 'Georgia', stateAbbr: 'GA', population: 498715 },
    { name: 'Columbus', state: 'Georgia', stateAbbr: 'GA', population: 206922 },
    { name: 'Augusta', state: 'Georgia', stateAbbr: 'GA', population: 202081 },
    { name: 'Savannah', state: 'Georgia', stateAbbr: 'GA', population: 147780 },
    { name: 'Athens', state: 'Georgia', stateAbbr: 'GA', population: 127315 },
    { name: 'Sandy Springs', state: 'Georgia', stateAbbr: 'GA', population: 108080 },
    { name: 'Roswell', state: 'Georgia', stateAbbr: 'GA', population: 92633 },
    { name: 'Macon', state: 'Georgia', stateAbbr: 'GA', population: 153159 },
    { name: 'Johns Creek', state: 'Georgia', stateAbbr: 'GA', population: 82453 },
    { name: 'Albany', state: 'Georgia', stateAbbr: 'GA', population: 69534 },
    { name: 'Warner Robins', state: 'Georgia', stateAbbr: 'GA', population: 80608 },
    { name: 'Alpharetta', state: 'Georgia', stateAbbr: 'GA', population: 67818 },
    { name: 'Marietta', state: 'Georgia', stateAbbr: 'GA', population: 60972 },
    { name: 'Valdosta', state: 'Georgia', stateAbbr: 'GA', population: 56050 },
    { name: 'Smyrna', state: 'Georgia', stateAbbr: 'GA', population: 56466 },
    { name: 'Dunwoody', state: 'Georgia', stateAbbr: 'GA', population: 50733 },
  ],
  'IL': [
    { name: 'Chicago', state: 'Illinois', stateAbbr: 'IL', population: 2693976 },
    { name: 'Aurora', state: 'Illinois', stateAbbr: 'IL', population: 180542 },
    { name: 'Naperville', state: 'Illinois', stateAbbr: 'IL', population: 149540 },
    { name: 'Joliet', state: 'Illinois', stateAbbr: 'IL', population: 150362 },
    { name: 'Rockford', state: 'Illinois', stateAbbr: 'IL', population: 148655 },
    { name: 'Elgin', state: 'Illinois', stateAbbr: 'IL', population: 114797 },
    { name: 'Peoria', state: 'Illinois', stateAbbr: 'IL', population: 113150 },
    { name: 'Champaign', state: 'Illinois', stateAbbr: 'IL', population: 88802 },
    { name: 'Waukegan', state: 'Illinois', stateAbbr: 'IL', population: 89103 },
    { name: 'Cicero', state: 'Illinois', stateAbbr: 'IL', population: 85268 },
    { name: 'Bloomington', state: 'Illinois', stateAbbr: 'IL', population: 78902 },
    { name: 'Arlington Heights', state: 'Illinois', stateAbbr: 'IL', population: 77676 },
    { name: 'Evanston', state: 'Illinois', stateAbbr: 'IL', population: 78239 },
    { name: 'Schaumburg', state: 'Illinois', stateAbbr: 'IL', population: 78673 },
    { name: 'Bolingbrook', state: 'Illinois', stateAbbr: 'IL', population: 73390 },
    { name: 'Palatine', state: 'Illinois', stateAbbr: 'IL', population: 67890 },
    { name: 'Skokie', state: 'Illinois', stateAbbr: 'IL', population: 67984 },
    { name: 'Des Plaines', state: 'Illinois', stateAbbr: 'IL', population: 60775 },
    { name: 'Orland Park', state: 'Illinois', stateAbbr: 'IL', population: 58387 },
    { name: 'Tinley Park', state: 'Illinois', stateAbbr: 'IL', population: 55971 },
    { name: 'Oak Lawn', state: 'Illinois', stateAbbr: 'IL', population: 56973 },
    { name: 'Berwyn', state: 'Illinois', stateAbbr: 'IL', population: 57652 },
    { name: 'Mount Prospect', state: 'Illinois', stateAbbr: 'IL', population: 56124 },
    { name: 'Normal', state: 'Illinois', stateAbbr: 'IL', population: 52241 },
    { name: 'Wheaton', state: 'Illinois', stateAbbr: 'IL', population: 53770 },
    { name: 'Hoffman Estates', state: 'Illinois', stateAbbr: 'IL', population: 51995 },
    { name: 'Oak Park', state: 'Illinois', stateAbbr: 'IL', population: 54483 },
    { name: 'Downers Grove', state: 'Illinois', stateAbbr: 'IL', population: 50197 },
  ],
  'TX': [
    { name: 'Houston', state: 'Texas', stateAbbr: 'TX', population: 2304580 },
    { name: 'San Antonio', state: 'Texas', stateAbbr: 'TX', population: 1547253 },
    { name: 'Dallas', state: 'Texas', stateAbbr: 'TX', population: 1343573 },
    { name: 'Austin', state: 'Texas', stateAbbr: 'TX', population: 978908 },
    { name: 'Fort Worth', state: 'Texas', stateAbbr: 'TX', population: 918915 },
    { name: 'El Paso', state: 'Texas', stateAbbr: 'TX', population: 678815 },
    { name: 'Arlington', state: 'Texas', stateAbbr: 'TX', population: 394266 },
    { name: 'Corpus Christi', state: 'Texas', stateAbbr: 'TX', population: 317863 },
    { name: 'Plano', state: 'Texas', stateAbbr: 'TX', population: 285494 },
    { name: 'Laredo', state: 'Texas', stateAbbr: 'TX', population: 256187 },
    { name: 'Lubbock', state: 'Texas', stateAbbr: 'TX', population: 257141 },
    { name: 'Garland', state: 'Texas', stateAbbr: 'TX', population: 246018 },
    { name: 'Irving', state: 'Texas', stateAbbr: 'TX', population: 256684 },
    { name: 'Amarillo', state: 'Texas', stateAbbr: 'TX', population: 200393 },
    { name: 'Grand Prairie', state: 'Texas', stateAbbr: 'TX', population: 196100 },
    { name: 'Brownsville', state: 'Texas', stateAbbr: 'TX', population: 186738 },
    { name: 'McKinney', state: 'Texas', stateAbbr: 'TX', population: 202690 },
    { name: 'Frisco', state: 'Texas', stateAbbr: 'TX', population: 200490 },
    { name: 'Pasadena', state: 'Texas', stateAbbr: 'TX', population: 153784 },
    { name: 'Killeen', state: 'Texas', stateAbbr: 'TX', population: 153095 },
    { name: 'Mesquite', state: 'Texas', stateAbbr: 'TX', population: 150108 },
    { name: 'McAllen', state: 'Texas', stateAbbr: 'TX', population: 142210 },
    { name: 'Carrollton', state: 'Texas', stateAbbr: 'TX', population: 133434 },
    { name: 'Midland', state: 'Texas', stateAbbr: 'TX', population: 132524 },
    { name: 'Denton', state: 'Texas', stateAbbr: 'TX', population: 139869 },
    { name: 'Abilene', state: 'Texas', stateAbbr: 'TX', population: 125182 },
    { name: 'Round Rock', state: 'Texas', stateAbbr: 'TX', population: 128812 },
    { name: 'Beaumont', state: 'Texas', stateAbbr: 'TX', population: 115282 },
    { name: 'Odessa', state: 'Texas', stateAbbr: 'TX', population: 121730 },
    { name: 'Waco', state: 'Texas', stateAbbr: 'TX', population: 138486 },
    { name: 'Richardson', state: 'Texas', stateAbbr: 'TX', population: 119469 },
    { name: 'Lewisville', state: 'Texas', stateAbbr: 'TX', population: 111822 },
    { name: 'Tyler', state: 'Texas', stateAbbr: 'TX', population: 105995 },
    { name: 'College Station', state: 'Texas', stateAbbr: 'TX', population: 120511 },
    { name: 'Pearland', state: 'Texas', stateAbbr: 'TX', population: 125828 },
    { name: 'San Angelo', state: 'Texas', stateAbbr: 'TX', population: 101004 },
    { name: 'Allen', state: 'Texas', stateAbbr: 'TX', population: 106874 },
    { name: 'League City', state: 'Texas', stateAbbr: 'TX', population: 111955 },
    { name: 'Sugar Land', state: 'Texas', stateAbbr: 'TX', population: 111026 },
    { name: 'Longview', state: 'Texas', stateAbbr: 'TX', population: 81729 },
    { name: 'Edinburg', state: 'Texas', stateAbbr: 'TX', population: 100243 },
    { name: 'Bryan', state: 'Texas', stateAbbr: 'TX', population: 86980 },
    { name: 'Baytown', state: 'Texas', stateAbbr: 'TX', population: 83701 },
    { name: 'Pharr', state: 'Texas', stateAbbr: 'TX', population: 79715 },
    { name: 'Missouri City', state: 'Texas', stateAbbr: 'TX', population: 74340 },
    { name: 'Temple', state: 'Texas', stateAbbr: 'TX', population: 82237 },
    { name: 'Flower Mound', state: 'Texas', stateAbbr: 'TX', population: 75802 },
    { name: 'Harlingen', state: 'Texas', stateAbbr: 'TX', population: 71829 },
    { name: 'New Braunfels', state: 'Texas', stateAbbr: 'TX', population: 90933 },
    { name: 'Conroe', state: 'Texas', stateAbbr: 'TX', population: 89856 },
    { name: 'Victoria', state: 'Texas', stateAbbr: 'TX', population: 65434 },
    { name: 'Cedar Park', state: 'Texas', stateAbbr: 'TX', population: 77259 },
    { name: 'Mansfield', state: 'Texas', stateAbbr: 'TX', population: 72778 },
    { name: 'Georgetown', state: 'Texas', stateAbbr: 'TX', population: 75526 },
    { name: 'Pflugerville', state: 'Texas', stateAbbr: 'TX', population: 65191 },
    { name: 'Port Arthur', state: 'Texas', stateAbbr: 'TX', population: 55724 },
    { name: 'Galveston', state: 'Texas', stateAbbr: 'TX', population: 53794 },
    { name: 'Rowlett', state: 'Texas', stateAbbr: 'TX', population: 62499 },
    { name: 'DeSoto', state: 'Texas', stateAbbr: 'TX', population: 54635 },
    { name: 'Wichita Falls', state: 'Texas', stateAbbr: 'TX', population: 104683 },
    { name: 'Lancaster', state: 'Texas', stateAbbr: 'TX', population: 41354 },
    { name: 'Lufkin', state: 'Texas', stateAbbr: 'TX', population: 35867 },
    { name: 'Sherman', state: 'Texas', stateAbbr: 'TX', population: 43645 },
    { name: 'Texarkana', state: 'Texas', stateAbbr: 'TX', population: 37333 },
  ],
  'NY': [
    { name: 'New York', state: 'New York', stateAbbr: 'NY', population: 8336817 },
    { name: 'Buffalo', state: 'New York', stateAbbr: 'NY', population: 276807 },
    { name: 'Rochester', state: 'New York', stateAbbr: 'NY', population: 211328 },
    { name: 'Yonkers', state: 'New York', stateAbbr: 'NY', population: 211569 },
    { name: 'Syracuse', state: 'New York', stateAbbr: 'NY', population: 148620 },
    { name: 'Albany', state: 'New York', stateAbbr: 'NY', population: 99124 },
    { name: 'New Rochelle', state: 'New York', stateAbbr: 'NY', population: 79446 },
    { name: 'Mount Vernon', state: 'New York', stateAbbr: 'NY', population: 73051 },
    { name: 'Schenectady', state: 'New York', stateAbbr: 'NY', population: 67047 },
    { name: 'Utica', state: 'New York', stateAbbr: 'NY', population: 65100 },
    { name: 'White Plains', state: 'New York', stateAbbr: 'NY', population: 59759 },
    { name: 'Hempstead', state: 'New York', stateAbbr: 'NY', population: 793409 },
    { name: 'Troy', state: 'New York', stateAbbr: 'NY', population: 51301 },
  ],
  'NC': [
    { name: 'Charlotte', state: 'North Carolina', stateAbbr: 'NC', population: 885708 },
    { name: 'Raleigh', state: 'North Carolina', stateAbbr: 'NC', population: 474069 },
    { name: 'Greensboro', state: 'North Carolina', stateAbbr: 'NC', population: 298263 },
    { name: 'Durham', state: 'North Carolina', stateAbbr: 'NC', population: 278993 },
    { name: 'Winston-Salem', state: 'North Carolina', stateAbbr: 'NC', population: 247945 },
    { name: 'Fayetteville', state: 'North Carolina', stateAbbr: 'NC', population: 208501 },
    { name: 'Cary', state: 'North Carolina', stateAbbr: 'NC', population: 174721 },
    { name: 'Wilmington', state: 'North Carolina', stateAbbr: 'NC', population: 115451 },
    { name: 'High Point', state: 'North Carolina', stateAbbr: 'NC', population: 114059 },
    { name: 'Concord', state: 'North Carolina', stateAbbr: 'NC', population: 105240 },
    { name: 'Asheville', state: 'North Carolina', stateAbbr: 'NC', population: 94298 },
    { name: 'Gastonia', state: 'North Carolina', stateAbbr: 'NC', population: 80899 },
    { name: 'Jacksonville', state: 'North Carolina', stateAbbr: 'NC', population: 72323 },
    { name: 'Chapel Hill', state: 'North Carolina', stateAbbr: 'NC', population: 61805 },
    { name: 'Rocky Mount', state: 'North Carolina', stateAbbr: 'NC', population: 54341 },
    { name: 'Burlington', state: 'North Carolina', stateAbbr: 'NC', population: 57043 },
    { name: 'Huntersville', state: 'North Carolina', stateAbbr: 'NC', population: 61296 },
    { name: 'Wilson', state: 'North Carolina', stateAbbr: 'NC', population: 47815 },
  ],
  'PA': [
    { name: 'Philadelphia', state: 'Pennsylvania', stateAbbr: 'PA', population: 1584064 },
    { name: 'Pittsburgh', state: 'Pennsylvania', stateAbbr: 'PA', population: 302971 },
    { name: 'Allentown', state: 'Pennsylvania', stateAbbr: 'PA', population: 125845 },
    { name: 'Erie', state: 'Pennsylvania', stateAbbr: 'PA', population: 101786 },
    { name: 'Reading', state: 'Pennsylvania', stateAbbr: 'PA', population: 95812 },
    { name: 'Scranton', state: 'Pennsylvania', stateAbbr: 'PA', population: 76914 },
    { name: 'Bethlehem', state: 'Pennsylvania', stateAbbr: 'PA', population: 75547 },
    { name: 'Lancaster', state: 'Pennsylvania', stateAbbr: 'PA', population: 59222 },
    { name: 'Harrisburg', state: 'Pennsylvania', stateAbbr: 'PA', population: 50099 },
    { name: 'Altoona', state: 'Pennsylvania', stateAbbr: 'PA', population: 43693 },
  ],
  'OH': [
    { name: 'Columbus', state: 'Ohio', stateAbbr: 'OH', population: 905748 },
    { name: 'Cleveland', state: 'Ohio', stateAbbr: 'OH', population: 383793 },
    { name: 'Cincinnati', state: 'Ohio', stateAbbr: 'OH', population: 309317 },
    { name: 'Toledo', state: 'Ohio', stateAbbr: 'OH', population: 270871 },
    { name: 'Akron', state: 'Ohio', stateAbbr: 'OH', population: 197597 },
    { name: 'Dayton', state: 'Ohio', stateAbbr: 'OH', population: 137644 },
    { name: 'Parma', state: 'Ohio', stateAbbr: 'OH', population: 81501 },
    { name: 'Canton', state: 'Ohio', stateAbbr: 'OH', population: 70435 },
    { name: 'Youngstown', state: 'Ohio', stateAbbr: 'OH', population: 60268 },
    { name: 'Lorain', state: 'Ohio', stateAbbr: 'OH', population: 65311 },
    { name: 'Hamilton', state: 'Ohio', stateAbbr: 'OH', population: 62777 },
    { name: 'Springfield', state: 'Ohio', stateAbbr: 'OH', population: 58298 },
    { name: 'Kettering', state: 'Ohio', stateAbbr: 'OH', population: 57147 },
    { name: 'Elyria', state: 'Ohio', stateAbbr: 'OH', population: 52346 },
    { name: 'Lakewood', state: 'Ohio', stateAbbr: 'OH', population: 50576 },
    { name: 'Cuyahoga Falls', state: 'Ohio', stateAbbr: 'OH', population: 50652 },
    { name: 'Middletown', state: 'Ohio', stateAbbr: 'OH', population: 50651 },
    { name: 'Newark', state: 'Ohio', stateAbbr: 'OH', population: 50664 },
  ],
  'MI': [
    { name: 'Detroit', state: 'Michigan', stateAbbr: 'MI', population: 639111 },
    { name: 'Grand Rapids', state: 'Michigan', stateAbbr: 'MI', population: 198917 },
    { name: 'Warren', state: 'Michigan', stateAbbr: 'MI', population: 139387 },
    { name: 'Sterling Heights', state: 'Michigan', stateAbbr: 'MI', population: 134346 },
    { name: 'Lansing', state: 'Michigan', stateAbbr: 'MI', population: 118210 },
    { name: 'Ann Arbor', state: 'Michigan', stateAbbr: 'MI', population: 123851 },
    { name: 'Flint', state: 'Michigan', stateAbbr: 'MI', population: 81005 },
    { name: 'Dearborn', state: 'Michigan', stateAbbr: 'MI', population: 109976 },
    { name: 'Livonia', state: 'Michigan', stateAbbr: 'MI', population: 95068 },
    { name: 'Troy', state: 'Michigan', stateAbbr: 'MI', population: 87294 },
    { name: 'Westland', state: 'Michigan', stateAbbr: 'MI', population: 84415 },
    { name: 'Farmington Hills', state: 'Michigan', stateAbbr: 'MI', population: 83186 },
    { name: 'Kalamazoo', state: 'Michigan', stateAbbr: 'MI', population: 73802 },
    { name: 'Wyoming', state: 'Michigan', stateAbbr: 'MI', population: 76001 },
    { name: 'Southfield', state: 'Michigan', stateAbbr: 'MI', population: 75645 },
    { name: 'Rochester Hills', state: 'Michigan', stateAbbr: 'MI', population: 76300 },
    { name: 'Taylor', state: 'Michigan', stateAbbr: 'MI', population: 63027 },
    { name: 'St. Clair Shores', state: 'Michigan', stateAbbr: 'MI', population: 58307 },
    { name: 'Pontiac', state: 'Michigan', stateAbbr: 'MI', population: 61181 },
    { name: 'Royal Oak', state: 'Michigan', stateAbbr: 'MI', population: 58303 },
  ],
  'WA': [
    { name: 'Seattle', state: 'Washington', stateAbbr: 'WA', population: 749256 },
    { name: 'Spokane', state: 'Washington', stateAbbr: 'WA', population: 228989 },
    { name: 'Tacoma', state: 'Washington', stateAbbr: 'WA', population: 219346 },
    { name: 'Vancouver', state: 'Washington', stateAbbr: 'WA', population: 190915 },
    { name: 'Bellevue', state: 'Washington', stateAbbr: 'WA', population: 151854 },
    { name: 'Kent', state: 'Washington', stateAbbr: 'WA', population: 132319 },
    { name: 'Everett', state: 'Washington', stateAbbr: 'WA', population: 110629 },
    { name: 'Renton', state: 'Washington', stateAbbr: 'WA', population: 106785 },
    { name: 'Yakima', state: 'Washington', stateAbbr: 'WA', population: 96868 },
    { name: 'Federal Way', state: 'Washington', stateAbbr: 'WA', population: 101030 },
    { name: 'Spokane Valley', state: 'Washington', stateAbbr: 'WA', population: 102976 },
    { name: 'Bellingham', state: 'Washington', stateAbbr: 'WA', population: 92589 },
    { name: 'Kennewick', state: 'Washington', stateAbbr: 'WA', population: 84347 },
    { name: 'Auburn', state: 'Washington', stateAbbr: 'WA', population: 87742 },
    { name: 'Pasco', state: 'Washington', stateAbbr: 'WA', population: 75108 },
    { name: 'Marysville', state: 'Washington', stateAbbr: 'WA', population: 70714 },
    { name: 'Lakewood', state: 'Washington', stateAbbr: 'WA', population: 63797 },
    { name: 'Redmond', state: 'Washington', stateAbbr: 'WA', population: 73256 },
    { name: 'Shoreline', state: 'Washington', stateAbbr: 'WA', population: 58381 },
    { name: 'Richland', state: 'Washington', stateAbbr: 'WA', population: 60175 },
    { name: 'Kirkland', state: 'Washington', stateAbbr: 'WA', population: 92854 },
    { name: 'Burien', state: 'Washington', stateAbbr: 'WA', population: 52066 },
    { name: 'Olympia', state: 'Washington', stateAbbr: 'WA', population: 55505 },
    { name: 'Lacey', state: 'Washington', stateAbbr: 'WA', population: 53626 },
  ],
  'NV': [
    { name: 'Las Vegas', state: 'Nevada', stateAbbr: 'NV', population: 641903 },
    { name: 'Henderson', state: 'Nevada', stateAbbr: 'NV', population: 317610 },
    { name: 'Reno', state: 'Nevada', stateAbbr: 'NV', population: 264165 },
    { name: 'North Las Vegas', state: 'Nevada', stateAbbr: 'NV', population: 262527 },
    { name: 'Sparks', state: 'Nevada', stateAbbr: 'NV', population: 108445 },
    { name: 'Carson City', state: 'Nevada', stateAbbr: 'NV', population: 58763 },
  ],
  'OR': [
    { name: 'Portland', state: 'Oregon', stateAbbr: 'OR', population: 652503 },
    { name: 'Salem', state: 'Oregon', stateAbbr: 'OR', population: 175535 },
    { name: 'Eugene', state: 'Oregon', stateAbbr: 'OR', population: 176654 },
    { name: 'Gresham', state: 'Oregon', stateAbbr: 'OR', population: 114247 },
    { name: 'Hillsboro', state: 'Oregon', stateAbbr: 'OR', population: 106894 },
    { name: 'Bend', state: 'Oregon', stateAbbr: 'OR', population: 102059 },
    { name: 'Beaverton', state: 'Oregon', stateAbbr: 'OR', population: 97802 },
    { name: 'Medford', state: 'Oregon', stateAbbr: 'OR', population: 85680 },
    { name: 'Springfield', state: 'Oregon', stateAbbr: 'OR', population: 64177 },
    { name: 'Corvallis', state: 'Oregon', stateAbbr: 'OR', population: 59422 },
    { name: 'Albany', state: 'Oregon', stateAbbr: 'OR', population: 56640 },
    { name: 'Tigard', state: 'Oregon', stateAbbr: 'OR', population: 54439 },
    { name: 'Lake Oswego', state: 'Oregon', stateAbbr: 'OR', population: 40571 },
    { name: 'Keizer', state: 'Oregon', stateAbbr: 'OR', population: 39376 },
  ],
  'UT': [
    { name: 'Salt Lake City', state: 'Utah', stateAbbr: 'UT', population: 200133 },
    { name: 'West Valley City', state: 'Utah', stateAbbr: 'UT', population: 140230 },
    { name: 'Provo', state: 'Utah', stateAbbr: 'UT', population: 115162 },
    { name: 'West Jordan', state: 'Utah', stateAbbr: 'UT', population: 116961 },
    { name: 'Orem', state: 'Utah', stateAbbr: 'UT', population: 97828 },
    { name: 'Sandy', state: 'Utah', stateAbbr: 'UT', population: 96253 },
    { name: 'Ogden', state: 'Utah', stateAbbr: 'UT', population: 87158 },
    { name: 'St. George', state: 'Utah', stateAbbr: 'UT', population: 95174 },
    { name: 'Layton', state: 'Utah', stateAbbr: 'UT', population: 81235 },
    { name: 'Taylorsville', state: 'Utah', stateAbbr: 'UT', population: 60448 },
    { name: 'Murray', state: 'Utah', stateAbbr: 'UT', population: 50637 },
    { name: 'Draper', state: 'Utah', stateAbbr: 'UT', population: 51517 },
    { name: 'South Jordan', state: 'Utah', stateAbbr: 'UT', population: 77529 },
    { name: 'Lehi', state: 'Utah', stateAbbr: 'UT', population: 75817 },
    { name: 'Logan', state: 'Utah', stateAbbr: 'UT', population: 52589 },
  ],
  'TN': [
    { name: 'Nashville', state: 'Tennessee', stateAbbr: 'TN', population: 689447 },
    { name: 'Memphis', state: 'Tennessee', stateAbbr: 'TN', population: 633104 },
    { name: 'Knoxville', state: 'Tennessee', stateAbbr: 'TN', population: 190740 },
    { name: 'Chattanooga', state: 'Tennessee', stateAbbr: 'TN', population: 181099 },
    { name: 'Clarksville', state: 'Tennessee', stateAbbr: 'TN', population: 166722 },
    { name: 'Murfreesboro', state: 'Tennessee', stateAbbr: 'TN', population: 152769 },
    { name: 'Franklin', state: 'Tennessee', stateAbbr: 'TN', population: 83954 },
    { name: 'Jackson', state: 'Tennessee', stateAbbr: 'TN', population: 68205 },
    { name: 'Johnson City', state: 'Tennessee', stateAbbr: 'TN', population: 71723 },
    { name: 'Bartlett', state: 'Tennessee', stateAbbr: 'TN', population: 59678 },
    { name: 'Hendersonville', state: 'Tennessee', stateAbbr: 'TN', population: 61441 },
    { name: 'Kingsport', state: 'Tennessee', stateAbbr: 'TN', population: 55239 },
  ],
  'IN': [
    { name: 'Indianapolis', state: 'Indiana', stateAbbr: 'IN', population: 887642 },
    { name: 'Fort Wayne', state: 'Indiana', stateAbbr: 'IN', population: 267927 },
    { name: 'Evansville', state: 'Indiana', stateAbbr: 'IN', population: 117429 },
    { name: 'South Bend', state: 'Indiana', stateAbbr: 'IN', population: 103453 },
    { name: 'Carmel', state: 'Indiana', stateAbbr: 'IN', population: 99157 },
    { name: 'Fishers', state: 'Indiana', stateAbbr: 'IN', population: 95722 },
    { name: 'Bloomington', state: 'Indiana', stateAbbr: 'IN', population: 79734 },
    { name: 'Hammond', state: 'Indiana', stateAbbr: 'IN', population: 77179 },
    { name: 'Gary', state: 'Indiana', stateAbbr: 'IN', population: 69593 },
    { name: 'Muncie', state: 'Indiana', stateAbbr: 'IN', population: 65994 },
    { name: 'Terre Haute', state: 'Indiana', stateAbbr: 'IN', population: 58572 },
    { name: 'Anderson', state: 'Indiana', stateAbbr: 'IN', population: 54568 },
  ],
  'MO': [
    { name: 'Kansas City', state: 'Missouri', stateAbbr: 'MO', population: 508090 },
    { name: 'St. Louis', state: 'Missouri', stateAbbr: 'MO', population: 301578 },
    { name: 'Springfield', state: 'Missouri', stateAbbr: 'MO', population: 169176 },
    { name: 'Columbia', state: 'Missouri', stateAbbr: 'MO', population: 126254 },
    { name: 'Independence', state: 'Missouri', stateAbbr: 'MO', population: 123011 },
    { name: 'Lee\'s Summit', state: 'Missouri', stateAbbr: 'MO', population: 101108 },
    { name: 'O\'Fallon', state: 'Missouri', stateAbbr: 'MO', population: 91407 },
    { name: 'St. Joseph', state: 'Missouri', stateAbbr: 'MO', population: 72215 },
    { name: 'St. Charles', state: 'Missouri', stateAbbr: 'MO', population: 79403 },
    { name: 'St. Peters', state: 'Missouri', stateAbbr: 'MO', population: 57792 },
    { name: 'Blue Springs', state: 'Missouri', stateAbbr: 'MO', population: 58604 },
    { name: 'Florissant', state: 'Missouri', stateAbbr: 'MO', population: 50232 },
  ],
  'MN': [
    { name: 'Minneapolis', state: 'Minnesota', stateAbbr: 'MN', population: 429606 },
    { name: 'St. Paul', state: 'Minnesota', stateAbbr: 'MN', population: 311527 },
    { name: 'Rochester', state: 'Minnesota', stateAbbr: 'MN', population: 121395 },
    { name: 'Duluth', state: 'Minnesota', stateAbbr: 'MN', population: 86297 },
    { name: 'Bloomington', state: 'Minnesota', stateAbbr: 'MN', population: 89387 },
    { name: 'Brooklyn Park', state: 'Minnesota', stateAbbr: 'MN', population: 86193 },
    { name: 'Plymouth', state: 'Minnesota', stateAbbr: 'MN', population: 81025 },
    { name: 'St. Cloud', state: 'Minnesota', stateAbbr: 'MN', population: 68581 },
    { name: 'Eagan', state: 'Minnesota', stateAbbr: 'MN', population: 68015 },
    { name: 'Woodbury', state: 'Minnesota', stateAbbr: 'MN', population: 75661 },
    { name: 'Maple Grove', state: 'Minnesota', stateAbbr: 'MN', population: 73356 },
    { name: 'Eden Prairie', state: 'Minnesota', stateAbbr: 'MN', population: 64028 },
    { name: 'Coon Rapids', state: 'Minnesota', stateAbbr: 'MN', population: 63224 },
    { name: 'Burnsville', state: 'Minnesota', stateAbbr: 'MN', population: 64079 },
    { name: 'Blaine', state: 'Minnesota', stateAbbr: 'MN', population: 70179 },
    { name: 'Lakeville', state: 'Minnesota', stateAbbr: 'MN', population: 69557 },
    { name: 'Minnetonka', state: 'Minnesota', stateAbbr: 'MN', population: 54628 },
    { name: 'Apple Valley', state: 'Minnesota', stateAbbr: 'MN', population: 56423 },
  ],
  'WI': [
    { name: 'Milwaukee', state: 'Wisconsin', stateAbbr: 'WI', population: 577222 },
    { name: 'Madison', state: 'Wisconsin', stateAbbr: 'WI', population: 269840 },
    { name: 'Green Bay', state: 'Wisconsin', stateAbbr: 'WI', population: 107395 },
    { name: 'Kenosha', state: 'Wisconsin', stateAbbr: 'WI', population: 99886 },
    { name: 'Racine', state: 'Wisconsin', stateAbbr: 'WI', population: 77240 },
    { name: 'Appleton', state: 'Wisconsin', stateAbbr: 'WI', population: 75720 },
    { name: 'Waukesha', state: 'Wisconsin', stateAbbr: 'WI', population: 71856 },
    { name: 'Oshkosh', state: 'Wisconsin', stateAbbr: 'WI', population: 66916 },
    { name: 'Eau Claire', state: 'Wisconsin', stateAbbr: 'WI', population: 69757 },
    { name: 'Janesville', state: 'Wisconsin', stateAbbr: 'WI', population: 65383 },
    { name: 'West Allis', state: 'Wisconsin', stateAbbr: 'WI', population: 59256 },
    { name: 'La Crosse', state: 'Wisconsin', stateAbbr: 'WI', population: 52297 },
  ],
  'MD': [
    { name: 'Baltimore', state: 'Maryland', stateAbbr: 'MD', population: 576498 },
    { name: 'Frederick', state: 'Maryland', stateAbbr: 'MD', population: 78938 },
    { name: 'Rockville', state: 'Maryland', stateAbbr: 'MD', population: 67979 },
    { name: 'Gaithersburg', state: 'Maryland', stateAbbr: 'MD', population: 69157 },
    { name: 'Bowie', state: 'Maryland', stateAbbr: 'MD', population: 58893 },
    { name: 'Annapolis', state: 'Maryland', stateAbbr: 'MD', population: 40927 },
    { name: 'College Park', state: 'Maryland', stateAbbr: 'MD', population: 34490 },
  ],
  'VA': [
    { name: 'Virginia Beach', state: 'Virginia', stateAbbr: 'VA', population: 459470 },
    { name: 'Norfolk', state: 'Virginia', stateAbbr: 'VA', population: 238005 },
    { name: 'Chesapeake', state: 'Virginia', stateAbbr: 'VA', population: 249422 },
    { name: 'Richmond', state: 'Virginia', stateAbbr: 'VA', population: 226610 },
    { name: 'Newport News', state: 'Virginia', stateAbbr: 'VA', population: 186247 },
    { name: 'Alexandria', state: 'Virginia', stateAbbr: 'VA', population: 159467 },
    { name: 'Hampton', state: 'Virginia', stateAbbr: 'VA', population: 137148 },
    { name: 'Portsmouth', state: 'Virginia', stateAbbr: 'VA', population: 97515 },
    { name: 'Suffolk', state: 'Virginia', stateAbbr: 'VA', population: 94224 },
    { name: 'Roanoke', state: 'Virginia', stateAbbr: 'VA', population: 100011 },
    { name: 'Lynchburg', state: 'Virginia', stateAbbr: 'VA', population: 79909 },
    { name: 'Harrisonburg', state: 'Virginia', stateAbbr: 'VA', population: 53101 },
    { name: 'Leesburg', state: 'Virginia', stateAbbr: 'VA', population: 53717 },
  ],
  'MA': [
    { name: 'Boston', state: 'Massachusetts', stateAbbr: 'MA', population: 692600 },
    { name: 'Worcester', state: 'Massachusetts', stateAbbr: 'MA', population: 206518 },
    { name: 'Springfield', state: 'Massachusetts', stateAbbr: 'MA', population: 155929 },
    { name: 'Lowell', state: 'Massachusetts', stateAbbr: 'MA', population: 115554 },
    { name: 'Cambridge', state: 'Massachusetts', stateAbbr: 'MA', population: 118403 },
    { name: 'New Bedford', state: 'Massachusetts', stateAbbr: 'MA', population: 101079 },
    { name: 'Brockton', state: 'Massachusetts', stateAbbr: 'MA', population: 105643 },
    { name: 'Quincy', state: 'Massachusetts', stateAbbr: 'MA', population: 101636 },
    { name: 'Lynn', state: 'Massachusetts', stateAbbr: 'MA', population: 101253 },
    { name: 'Fall River', state: 'Massachusetts', stateAbbr: 'MA', population: 94294 },
    { name: 'Newton', state: 'Massachusetts', stateAbbr: 'MA', population: 88417 },
    { name: 'Lawrence', state: 'Massachusetts', stateAbbr: 'MA', population: 89143 },
    { name: 'Somerville', state: 'Massachusetts', stateAbbr: 'MA', population: 81275 },
  ],
  'NJ': [
    { name: 'Newark', state: 'New Jersey', stateAbbr: 'NJ', population: 311549 },
    { name: 'Jersey City', state: 'New Jersey', stateAbbr: 'NJ', population: 292449 },
    { name: 'Paterson', state: 'New Jersey', stateAbbr: 'NJ', population: 159732 },
    { name: 'Elizabeth', state: 'New Jersey', stateAbbr: 'NJ', population: 137298 },
    { name: 'Edison', state: 'New Jersey', stateAbbr: 'NJ', population: 107588 },
    { name: 'Woodbridge', state: 'New Jersey', stateAbbr: 'NJ', population: 103639 },
    { name: 'Lakewood', state: 'New Jersey', stateAbbr: 'NJ', population: 135158 },
    { name: 'Toms River', state: 'New Jersey', stateAbbr: 'NJ', population: 95028 },
    { name: 'Hamilton', state: 'New Jersey', stateAbbr: 'NJ', population: 92124 },
    { name: 'Trenton', state: 'New Jersey', stateAbbr: 'NJ', population: 90632 },
    { name: 'Clifton', state: 'New Jersey', stateAbbr: 'NJ', population: 90368 },
    { name: 'Camden', state: 'New Jersey', stateAbbr: 'NJ', population: 73743 },
    { name: 'Brick', state: 'New Jersey', stateAbbr: 'NJ', population: 75521 },
    { name: 'Cherry Hill', state: 'New Jersey', stateAbbr: 'NJ', population: 74678 },
    { name: 'Passaic', state: 'New Jersey', stateAbbr: 'NJ', population: 71009 },
  ],
  'CT': [
    { name: 'Bridgeport', state: 'Connecticut', stateAbbr: 'CT', population: 148654 },
    { name: 'New Haven', state: 'Connecticut', stateAbbr: 'CT', population: 135081 },
    { name: 'Hartford', state: 'Connecticut', stateAbbr: 'CT', population: 121054 },
    { name: 'Stamford', state: 'Connecticut', stateAbbr: 'CT', population: 135470 },
    { name: 'Waterbury', state: 'Connecticut', stateAbbr: 'CT', population: 114403 },
    { name: 'Norwalk', state: 'Connecticut', stateAbbr: 'CT', population: 91294 },
    { name: 'Danbury', state: 'Connecticut', stateAbbr: 'CT', population: 86518 },
    { name: 'New Britain', state: 'Connecticut', stateAbbr: 'CT', population: 74559 },
    { name: 'West Hartford', state: 'Connecticut', stateAbbr: 'CT', population: 63776 },
    { name: 'Greenwich', state: 'Connecticut', stateAbbr: 'CT', population: 63495 },
    { name: 'Hamden', state: 'Connecticut', stateAbbr: 'CT', population: 61412 },
    { name: 'Meriden', state: 'Connecticut', stateAbbr: 'CT', population: 60850 },
  ],
  'SC': [
    { name: 'Charleston', state: 'South Carolina', stateAbbr: 'SC', population: 150227 },
    { name: 'Columbia', state: 'South Carolina', stateAbbr: 'SC', population: 136632 },
    { name: 'North Charleston', state: 'South Carolina', stateAbbr: 'SC', population: 115382 },
    { name: 'Mount Pleasant', state: 'South Carolina', stateAbbr: 'SC', population: 91312 },
    { name: 'Rock Hill', state: 'South Carolina', stateAbbr: 'SC', population: 74448 },
    { name: 'Greenville', state: 'South Carolina', stateAbbr: 'SC', population: 72495 },
    { name: 'Summerville', state: 'South Carolina', stateAbbr: 'SC', population: 51915 },
    { name: 'Sumter', state: 'South Carolina', stateAbbr: 'SC', population: 43463 },
    { name: 'Hilton Head Island', state: 'South Carolina', stateAbbr: 'SC', population: 37299 },
  ],
  'LA': [
    { name: 'New Orleans', state: 'Louisiana', stateAbbr: 'LA', population: 383997 },
    { name: 'Baton Rouge', state: 'Louisiana', stateAbbr: 'LA', population: 227470 },
    { name: 'Shreveport', state: 'Louisiana', stateAbbr: 'LA', population: 187593 },
    { name: 'Lafayette', state: 'Louisiana', stateAbbr: 'LA', population: 121374 },
    { name: 'Lake Charles', state: 'Louisiana', stateAbbr: 'LA', population: 84352 },
    { name: 'Kenner', state: 'Louisiana', stateAbbr: 'LA', population: 66102 },
    { name: 'Bossier City', state: 'Louisiana', stateAbbr: 'LA', population: 62741 },
    { name: 'Monroe', state: 'Louisiana', stateAbbr: 'LA', population: 47902 },
  ],
  'KY': [
    { name: 'Louisville', state: 'Kentucky', stateAbbr: 'KY', population: 628594 },
    { name: 'Lexington', state: 'Kentucky', stateAbbr: 'KY', population: 322570 },
    { name: 'Bowling Green', state: 'Kentucky', stateAbbr: 'KY', population: 72894 },
    { name: 'Owensboro', state: 'Kentucky', stateAbbr: 'KY', population: 60183 },
    { name: 'Covington', state: 'Kentucky', stateAbbr: 'KY', population: 40840 },
  ],
  'OK': [
    { name: 'Oklahoma City', state: 'Oklahoma', stateAbbr: 'OK', population: 681054 },
    { name: 'Tulsa', state: 'Oklahoma', stateAbbr: 'OK', population: 413066 },
    { name: 'Norman', state: 'Oklahoma', stateAbbr: 'OK', population: 128026 },
    { name: 'Broken Arrow', state: 'Oklahoma', stateAbbr: 'OK', population: 113540 },
    { name: 'Lawton', state: 'Oklahoma', stateAbbr: 'OK', population: 90621 },
    { name: 'Edmond', state: 'Oklahoma', stateAbbr: 'OK', population: 94654 },
    { name: 'Moore', state: 'Oklahoma', stateAbbr: 'OK', population: 62813 },
    { name: 'Midwest City', state: 'Oklahoma', stateAbbr: 'OK', population: 60408 },
  ],
  'IA': [
    { name: 'Des Moines', state: 'Iowa', stateAbbr: 'IA', population: 214133 },
    { name: 'Cedar Rapids', state: 'Iowa', stateAbbr: 'IA', population: 137710 },
    { name: 'Davenport', state: 'Iowa', stateAbbr: 'IA', population: 101724 },
    { name: 'Sioux City', state: 'Iowa', stateAbbr: 'IA', population: 85618 },
    { name: 'Iowa City', state: 'Iowa', stateAbbr: 'IA', population: 74898 },
    { name: 'Waterloo', state: 'Iowa', stateAbbr: 'IA', population: 67199 },
    { name: 'Council Bluffs', state: 'Iowa', stateAbbr: 'IA', population: 62598 },
    { name: 'Ames', state: 'Iowa', stateAbbr: 'IA', population: 66391 },
  ],
  'AR': [
    { name: 'Little Rock', state: 'Arkansas', stateAbbr: 'AR', population: 202591 },
    { name: 'Fort Smith', state: 'Arkansas', stateAbbr: 'AR', population: 89342 },
    { name: 'Fayetteville', state: 'Arkansas', stateAbbr: 'AR', population: 93948 },
    { name: 'Springdale', state: 'Arkansas', stateAbbr: 'AR', population: 84615 },
    { name: 'Jonesboro', state: 'Arkansas', stateAbbr: 'AR', population: 78676 },
    { name: 'North Little Rock', state: 'Arkansas', stateAbbr: 'AR', population: 64838 },
    { name: 'Conway', state: 'Arkansas', stateAbbr: 'AR', population: 67461 },
    { name: 'Rogers', state: 'Arkansas', stateAbbr: 'AR', population: 69496 },
  ],
  'MS': [
    { name: 'Jackson', state: 'Mississippi', stateAbbr: 'MS', population: 153701 },
    { name: 'Gulfport', state: 'Mississippi', stateAbbr: 'MS', population: 72304 },
    { name: 'Southaven', state: 'Mississippi', stateAbbr: 'MS', population: 54882 },
    { name: 'Hattiesburg', state: 'Mississippi', stateAbbr: 'MS', population: 48914 },
  ],
  'KS': [
    { name: 'Wichita', state: 'Kansas', stateAbbr: 'KS', population: 397532 },
    { name: 'Overland Park', state: 'Kansas', stateAbbr: 'KS', population: 197238 },
    { name: 'Kansas City', state: 'Kansas', stateAbbr: 'KS', population: 156607 },
    { name: 'Olathe', state: 'Kansas', stateAbbr: 'KS', population: 141290 },
    { name: 'Topeka', state: 'Kansas', stateAbbr: 'KS', population: 126587 },
    { name: 'Lawrence', state: 'Kansas', stateAbbr: 'KS', population: 98448 },
    { name: 'Shawnee', state: 'Kansas', stateAbbr: 'KS', population: 67935 },
    { name: 'Manhattan', state: 'Kansas', stateAbbr: 'KS', population: 54100 },
  ],
  'NM': [
    { name: 'Albuquerque', state: 'New Mexico', stateAbbr: 'NM', population: 564559 },
    { name: 'Las Cruces', state: 'New Mexico', stateAbbr: 'NM', population: 111385 },
    { name: 'Rio Rancho', state: 'New Mexico', stateAbbr: 'NM', population: 104046 },
    { name: 'Santa Fe', state: 'New Mexico', stateAbbr: 'NM', population: 87505 },
    { name: 'Roswell', state: 'New Mexico', stateAbbr: 'NM', population: 48066 },
  ],
  'NE': [
    { name: 'Omaha', state: 'Nebraska', stateAbbr: 'NE', population: 486051 },
    { name: 'Lincoln', state: 'Nebraska', stateAbbr: 'NE', population: 291082 },
    { name: 'Bellevue', state: 'Nebraska', stateAbbr: 'NE', population: 64176 },
    { name: 'Grand Island', state: 'Nebraska', stateAbbr: 'NE', population: 53131 },
  ],
  'ID': [
    { name: 'Boise', state: 'Idaho', stateAbbr: 'ID', population: 235684 },
    { name: 'Nampa', state: 'Idaho', stateAbbr: 'ID', population: 100200 },
    { name: 'Meridian', state: 'Idaho', stateAbbr: 'ID', population: 117635 },
    { name: 'Idaho Falls', state: 'Idaho', stateAbbr: 'ID', population: 64975 },
    { name: 'Pocatello', state: 'Idaho', stateAbbr: 'ID', population: 56720 },
    { name: 'Caldwell', state: 'Idaho', stateAbbr: 'ID', population: 59996 },
  ],
  'HI': [
    { name: 'Honolulu', state: 'Hawaii', stateAbbr: 'HI', population: 350964 },
  ],
  'NH': [
    { name: 'Manchester', state: 'New Hampshire', stateAbbr: 'NH', population: 115644 },
    { name: 'Nashua', state: 'New Hampshire', stateAbbr: 'NH', population: 91247 },
    { name: 'Concord', state: 'New Hampshire', stateAbbr: 'NH', population: 43776 },
  ],
  'ME': [
    { name: 'Portland', state: 'Maine', stateAbbr: 'ME', population: 68208 },
  ],
  'RI': [
    { name: 'Providence', state: 'Rhode Island', stateAbbr: 'RI', population: 190934 },
    { name: 'Warwick', state: 'Rhode Island', stateAbbr: 'RI', population: 82623 },
    { name: 'Cranston', state: 'Rhode Island', stateAbbr: 'RI', population: 82701 },
    { name: 'Pawtucket', state: 'Rhode Island', stateAbbr: 'RI', population: 75604 },
  ],
  'WV': [
    { name: 'Charleston', state: 'West Virginia', stateAbbr: 'WV', population: 46736 },
    { name: 'Huntington', state: 'West Virginia', stateAbbr: 'WV', population: 46049 },
  ],
  'DE': [
    { name: 'Wilmington', state: 'Delaware', stateAbbr: 'DE', population: 70851 },
    { name: 'Dover', state: 'Delaware', stateAbbr: 'DE', population: 39023 },
  ],
  'SD': [
    { name: 'Sioux Falls', state: 'South Dakota', stateAbbr: 'SD', population: 192517 },
    { name: 'Rapid City', state: 'South Dakota', stateAbbr: 'SD', population: 74903 },
  ],
  'ND': [
    { name: 'Fargo', state: 'North Dakota', stateAbbr: 'ND', population: 125990 },
    { name: 'Bismarck', state: 'North Dakota', stateAbbr: 'ND', population: 73622 },
    { name: 'Grand Forks', state: 'North Dakota', stateAbbr: 'ND', population: 59166 },
  ],
  'MT': [
    { name: 'Billings', state: 'Montana', stateAbbr: 'MT', population: 117116 },
    { name: 'Missoula', state: 'Montana', stateAbbr: 'MT', population: 75916 },
    { name: 'Great Falls', state: 'Montana', stateAbbr: 'MT', population: 60638 },
    { name: 'Bozeman', state: 'Montana', stateAbbr: 'MT', population: 53493 },
  ],
  'AK': [
    { name: 'Anchorage', state: 'Alaska', stateAbbr: 'AK', population: 291247 },
    { name: 'Fairbanks', state: 'Alaska', stateAbbr: 'AK', population: 32324 },
  ],
  'VT': [
    { name: 'Burlington', state: 'Vermont', stateAbbr: 'VT', population: 44943 },
  ],
  'WY': [
    { name: 'Cheyenne', state: 'Wyoming', stateAbbr: 'WY', population: 65132 },
    { name: 'Casper', state: 'Wyoming', stateAbbr: 'WY', population: 59448 },
  ],
}

// Get all cities with population 50,000+
export function getAllUSCities(): USCity[] {
  return Object.values(usCitiesByState).flat()
}

// Get cities for a specific state
export function getCitiesForState(stateAbbr: string): USCity[] {
  return usCitiesByState[stateAbbr.toUpperCase()] || []
}

// Get state abbreviation for a city
export function getStateForCity(cityName: string): { state: string; stateAbbr: string } | null {
  const normalizedCity = cityName.trim()
  
  for (const [stateAbbr, cities] of Object.entries(usCitiesByState)) {
    const city = cities.find(c => 
      c.name.toLowerCase() === normalizedCity.toLowerCase()
    )
    if (city) {
      return { state: city.state, stateAbbr: city.stateAbbr }
    }
  }
  
  return null
}

// Search cities by name (supports partial matching)
export function searchCities(query: string, limit: number = 10): USCity[] {
  if (!query || query.length < 1) return []
  
  const normalizedQuery = query.toLowerCase().trim()
  const allCities = getAllUSCities()
  
  // First, try exact start matches, then partial matches
  const matches = allCities.filter(city => {
    const cityLower = city.name.toLowerCase()
    return cityLower.startsWith(normalizedQuery) || cityLower.includes(normalizedQuery)
  })
  
  // Sort: exact start matches first, then by population (descending)
  matches.sort((a, b) => {
    const aStarts = a.name.toLowerCase().startsWith(normalizedQuery)
    const bStarts = b.name.toLowerCase().startsWith(normalizedQuery)
    
    if (aStarts && !bStarts) return -1
    if (!aStarts && bStarts) return 1
    return b.population - a.population // Higher population first
  })
  
  return matches.slice(0, limit)
}

